[build]
  publish = "dist"
  command = "nuxt generate"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "andre-van-tonder"
    sentryProject = "drevan-me"

[[redirects]]
  from = "https://www.drevantonder.io/*"
  to = "https://drevan.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://drevantonder.io/*"
  to = "https://drevan.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.drevan.me/*"
  to = "https://drevan.me/:splat"
  status = 301
  force = true
