import './styles.css'
import { Lexend_Deca } from 'next/font/google'
import { Container } from '@/components/Container'
import Link from 'next/link'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  variable: '--custom-font',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${lexendDeca.variable} font-sans`}>
      <body>
        <Container>
          <nav className="mt-8">
            <ul className="flex space-x-8">
              <li><Link className="font-medium text-gray-600" href="/">home</Link></li>
              <li><Link className="font-medium text-gray-600" href="/photos/">@photosbydrevan</Link></li>
              <li><Link className="font-medium text-gray-600" href="/blog">blog</Link></li>
            </ul>
          </nav>
          <main className="mt-32">
          {children}
          </main>
        </Container>
      </body>
    </html>
  )
}
