import './styles.css'
import { Lexend_Deca } from 'next/font/google'

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  variable: '--custom-font',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${lexendDeca.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
